// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.abaddon.practices.powermock.testingsprinroo.dominio;

import com.abaddon.practices.powermock.testingsprinroo.dominio.Persona;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Persona_Roo_Entity {
    
    declare @type: Persona: @Entity;
    
    @PersistenceContext
    transient EntityManager Persona.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Persona.id;
    
    @Version
    @Column(name = "version")
    private Integer Persona.version;
    
    public Long Persona.getId() {
        return this.id;
    }
    
    public void Persona.setId(Long id) {
        this.id = id;
    }
    
    public Integer Persona.getVersion() {
        return this.version;
    }
    
    public void Persona.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void Persona.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Persona.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Persona attached = Persona.findPersona(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Persona.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Persona.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Persona Persona.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Persona merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Persona.entityManager() {
        EntityManager em = new Persona().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Persona.countPersonae() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Persona o", Long.class).getSingleResult();
    }
    
    public static List<Persona> Persona.findAllPersonae() {
        return entityManager().createQuery("SELECT o FROM Persona o", Persona.class).getResultList();
    }
    
    public static Persona Persona.findPersona(Long id) {
        if (id == null) return null;
        return entityManager().find(Persona.class, id);
    }
    
    public static List<Persona> Persona.findPersonaEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Persona o", Persona.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
