// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.abaddon.practices.powermock.testingsprinroo.dominio;

import java.lang.String;

privileged aspect Persona_Roo_JavaBean {
    
    public String Persona.getNombre() {
        return this.nombre;
    }
    
    public void Persona.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public String Persona.getApellido() {
        return this.apellido;
    }
    
    public void Persona.setApellido(String apellido) {
        this.apellido = apellido;
    }
    
}
